language: node_js
node_js:
  - "0.10"

before_install:
  - npm install -g bower grunt-cli
  - bower install

script: "grunt publish"

env:
  global:
    secure: EmjGZyMST15FoQQSgJwSuTQDFlSknXOMs9BbfKRhgvWDPnYR1fMEBL/Kjxasp8sYu7GEZ4nPwGIJX4rCB/x0ixaOOPMlJ1pq/hG3cD/y8KHvmeX5sNJ9UVtIop0mv9aaqD66MAMadBI1qCidwpW+FLL5E1CrG6+D3sMkWwxZyNc=
